/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TabFromTorootImport } from './routes/$tab/$from/$to/__root'

// Create Virtual Routes

const TabFromToImport = createFileRoute('/$tab/$from/$to')()

// Create/Update Routes

const TabFromTorootRoute = TabFromTorootImport.update({
  id: '/__root',
  getParentRoute: () => TabFromToRoute,
} as any)

const TabFromToRoute = TabFromToImport.update({
  path: '/$tab/$from/$to',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$tab/$from/$to': {
      id: '/$tab/$from/$to'
      path: '/$tab/$from/$to'
      fullPath: '/$tab/$from/$to'
      preLoaderRoute: typeof TabFromToImport
      parentRoute: typeof rootRoute
    }
    '/$tab/$from/$to/__root': {
      id: '/$tab/$from/$to/__root'
      path: '/$tab/$from/$to'
      fullPath: '/$tab/$from/$to'
      preLoaderRoute: typeof TabFromTorootImport
      parentRoute: typeof TabFromToRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  TabFromToRoute: TabFromToRoute.addChildren({}),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/$tab/$from/$to"
      ]
    },
    "/$tab/$from/$to": {
      "filePath": "$tab/$from/$to",
      "children": [
        "/$tab/$from/$to/__root"
      ]
    },
    "/$tab/$from/$to/__root": {
      "filePath": "$tab/$from/$to/__root.tsx",
      "parent": "/$tab/$from/$to"
    }
  }
}
ROUTE_MANIFEST_END */
